name: openxc
description: OpenXC
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^6.0.0
  get_it_hooks: ^2.0.0
  flutter_hooks: ^0.16.0
  flutter_blue: ^0.8.0
  flutter_spinkit: ^4.1.2
  badges: ^2.0.1
  shared_preferences: ^2.0.6
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: launcher_icon
  adaptive_icon_background: "#181A20"
  adaptive_icon_foreground: assets/icon/OpenXC-Foreground.png
  ios: true
  remove_alpha_ios: true
  image_path: assets/icon/OpenXC.png

flutter:
  uses-material-design: true
  fonts:
      - family: Comfortaa
        fonts:
          - asset: assets/font/Comfortaa.ttf